stages:
  - test

test_job:
  stage: test
  image: eclipse-temurin:17-jdk-focal
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  script:
    - echo "Checking out code and running tests..."
    - chmod +x ./gradlew
    - ./gradlew build --no-daemon
    - ./gradlew test --no-daemon
  cache:
    key: "${CI_RUNNER_OS}-gradle-${CI_COMMIT_SHA}"
    paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper
    policy: pull-push