spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookdb}
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  secret: ${JWT_SECRET_KEY:your_key}
  expiration: 86400000

cache:
  redis:
    ttl: 60
  pool:
    core-size: 4
    max-size: 10
    queue-capacity: 100
    thread-name-prefix: CacheThread-

server:
  port: 8080